import { Inter } from "next/font/google";
import Topbar from "@/components/Topbar";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Online Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-full w-full">
        <div className="flex flex-1  w-screen">
          <Sidebar />
          </div>
          <div className="flex flex-col w-screen h-full">
          <Topbar />
            <main className="flex flex-col flex-1">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
